apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pr-test
  title: Test Template with PR
  description: A template that generates changes and opens a pull request using Backstage Scaffolder.
spec:
  type: service
  parameters:
    properties:
      appName:
        title: Application Name
        type: string
        description: Provide a name of application.
      repoUrl:
        title: Application Url
        type: string
        description: Provide a url to application.
      technology:
        title: Technology
        type: string
        description: Select the technology stack for the project.
        enum: ["Node.js", "Python", "Java"]
    required: ["appName", "repoUrl", "technology"]  
  steps:
    - id: generate-files
      name: Generate Files
      action: cookiecutter
      input:
        templatePath: ./template-files
    - id: publish
      name: Publish to GitHub and Create PR
      action: publish:github
      input:
        repoUrl: https://github.com/your-org/your-repo
        targetPath: "./"
        commitMessage: "Add test changes via Backstage Scaffolder"
        branchName: "pr-test-branch"
        pullRequestTitle: "${{ parameters.prTitle }}"
        pullRequestDescription: "Automatically generated pull request using Backstage Scaffolder."
